name: Rustlings Progress Update

on:
  push:
    branches:
      - main

jobs:
  Progress-Update:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dogoo-me/rustlings-progress@v1
        with:
          github_token: ${{ github.token }}